name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version
        run: corepack prepare yarn@4.9.1 --activate
  
      - name: Install dependencies
        run: yarn install
  
      - name: Build project
        run: yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4